- hosts: all
  tasks:
    - name: create vsphere guest
      delegate_to: localhost
      community.vmware.vmware_guest:
        validate_certs: false
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        name: "{{ name }}"
        folder: "{{ folder }}"
        hardware: "{{ hardware }}"
        networks: "{{ networks }}"
        disk: "{{ disk }}"
        cluster: "{{ cluster }}"
        state: "{{ state }}"
        guest_id: "{{ guest_id }}"
